-- Snapshots diarios de conjuntos/anuncios. O dashboard consulta apenas o
-- Supabase; a Meta fica restrita ao job de sincronizacao em background.
create table if not exists public.meta_ad_level_metrics (
  id bigint generated by default as identity primary key,
  meta_account_id uuid references public.meta_ad_accounts(id) on delete cascade,
  ad_account_id text not null,
  level text not null check (level in ('adset', 'ad')),
  external_id text not null,
  name text not null,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  campaign_name text not null,
  adset_external_id text,
  adset_name text,
  date date not null,
  amount_spent numeric(14, 4) not null default 0,
  impressions bigint not null default 0,
  clicks bigint not null default 0,
  result_count numeric(14, 2) not null default 0,
  result_label text not null default 'Resultados',
  currency text not null default 'BRL',
  updated_at timestamptz not null default now(),
  unique (level, ad_account_id, external_id, date)
);

create index if not exists meta_ad_level_metrics_level_date_idx
  on public.meta_ad_level_metrics (level, date desc);

create index if not exists meta_ad_level_metrics_campaign_level_date_idx
  on public.meta_ad_level_metrics (campaign_id, level, date desc);

create index if not exists meta_ad_level_metrics_adset_date_idx
  on public.meta_ad_level_metrics (adset_external_id, date desc)
  where adset_external_id is not null;

alter table public.meta_ad_level_metrics enable row level security;

-- A tabela nao e uma API publica. Somente o backend com service_role ingere e
-- le os snapshots; paginas autenticadas continuam passando pela autorizacao do
-- servidor e nunca recebem credenciais privilegiadas.
revoke all on table public.meta_ad_level_metrics from anon, authenticated;
grant select, insert, update on table public.meta_ad_level_metrics to service_role;
grant usage, select on sequence public.meta_ad_level_metrics_id_seq to service_role;

create or replace function public.get_meta_ad_level_summary(
  p_level text,
  p_start date,
  p_end date,
  p_campaign_ids uuid[] default null,
  p_adset_external_id text default null
)
returns table (
  external_id text,
  name text,
  campaign_id uuid,
  campaign_name text,
  adset_external_id text,
  adset_name text,
  amount_spent numeric,
  impressions bigint,
  clicks bigint,
  result_count numeric,
  result_label text,
  currency text
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    metric.external_id,
    (array_agg(metric.name order by metric.date desc))[1] as name,
    metric.campaign_id,
    (array_agg(metric.campaign_name order by metric.date desc))[1] as campaign_name,
    metric.adset_external_id,
    (array_agg(metric.adset_name order by metric.date desc))[1] as adset_name,
    sum(metric.amount_spent) as amount_spent,
    sum(metric.impressions)::bigint as impressions,
    sum(metric.clicks)::bigint as clicks,
    sum(metric.result_count) as result_count,
    (array_agg(metric.result_label order by metric.date desc))[1] as result_label,
    metric.currency
  from public.meta_ad_level_metrics as metric
  where metric.level = p_level
    and metric.date between p_start and p_end
    and (p_campaign_ids is null or metric.campaign_id = any(p_campaign_ids))
    and (p_adset_external_id is null or metric.adset_external_id = p_adset_external_id)
  group by
    metric.external_id,
    metric.campaign_id,
    metric.adset_external_id,
    metric.currency
  order by sum(metric.amount_spent) desc;
$$;

revoke all on function public.get_meta_ad_level_summary(text, date, date, uuid[], text)
  from public, anon, authenticated;
grant execute on function public.get_meta_ad_level_summary(text, date, date, uuid[], text)
  to service_role;
